/**
 * Copyright © 2024 Apple Inc. and the Pkl project authors. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.pkl.core.runtime.test.jqwik;

import java.util.Optional;

/**
 * Use this superclass if you want to provide a specialized type of arbitrary, e.g. with additional
 * methods for configuration or defaults, but don't want to implement the whole {@linkplain
 * Arbitrary} interface yourself.
 *
 * @param <T> The type of object to be generated by this arbitrary
 * @see Arbitrary
 * @see Arbitraries
 */
public abstract class ArbitraryDecorator<T> implements Cloneable, Arbitrary<T> {

  private Arbitrary<T> instance = null;

  /**
   * Implement by calling jqwik's standard DSL for building arbitraries.
   *
   * @return a new arbitrary instance
   */
  protected abstract Arbitrary<T> arbitrary();

  private Arbitrary<T> instance() {
    if (instance == null) {
      instance = arbitrary();
    }
    return instance;
  }

  @Override
  public RandomGenerator<T> generator(int genSize) {
    return instance().generator(genSize);
  }

  @Override
  public RandomGenerator<T> generatorWithEmbeddedEdgeCases(int genSize) {
    return instance().generatorWithEmbeddedEdgeCases(genSize);
  }

  @Override
  public Optional<ExhaustiveGenerator<T>> exhaustive(long maxNumberOfSamples) {
    return instance().exhaustive(maxNumberOfSamples);
  }

  @Override
  public boolean isGeneratorMemoizable() {
    return instance().isGeneratorMemoizable();
  }

  @Override
  public EdgeCases<T> edgeCases(int maxEdgeCases) {
    return instance().edgeCases(maxEdgeCases);
  }

  @Override
  public String toString() {
    return String.format("Decorated:%s", super.toString());
  }

  /**
   * Use to clone current instance with its interface type
   *
   * @param <A> The special interface type of this arbitrary
   * @return A cloned instance of this arbitrary
   */
  @SuppressWarnings("unchecked")
  protected <A extends Arbitrary<?>> A typedClone() {
    try {
      return (A) this.clone();
    } catch (CloneNotSupportedException e) {
      throw new JqwikException(e.getMessage());
    }
  }
}
